
language: node_js
node_js:
  - 6
cache:
  directories:
    - node_modules
install:
  - yarn install
script:
  - yarn run test | tee output.txt; test ${PIPESTATUS[0]} -eq 0
after_failure:
  - yarn run log